name: Deploy web to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate new Docker image tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          cat <<EOF > .env
          ${{ secrets.DEV_ENV }}
          EOF
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/suivi_encaissement_web:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/suivi_encaissement_web:${{ env.IMAGE_TAG }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/suivi-encaissement-web

            echo "📥 Pulling new Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/suivi_encaissement_web:${{ env.IMAGE_TAG }}

            echo "🔄 Updating docker-compose.yml with new image tag..."
            sed -i 's|image: ${{ secrets.DOCKERHUB_USERNAME }}/suivi_encaissement_web:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/suivi_encaissement_web:${{ env.IMAGE_TAG }}|' docker-compose.yml

            echo "🛑 Stopping existing containers..."
            docker-compose down -v

            echo "🚀 Starting updated containers..."
            docker-compose up -d --remove-orphans

            echo "✅ Deployment complete!"
